### Health Check
GET http://127.0.0.1:8000/health_check

### Health Check
GET https://zero2prod-v5cnw.ondigitalocean.app/health_check

###


POST http://127.0.0.1:8000/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin &
email=ursula_le_guin%40gmail.com


###

POST https://zero2prod-v5cnw.ondigitalocean.app/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin &
email=ursula_le_guin%40gmail.com



