name: "CI pipeline"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Cargo test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/tarpaulin@v0.1.0
      - run: cargo test --all-features
      - run: cargo tarpaulin --ignore-tests
      - run: cargo audit